import type { Metadata } from "next";
import { Varela_Round } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { ThemeProvider } from "@/components/theme-provider";
import { AppWrapper } from "@/context";
import { Toaster } from "sonner";

const varela = Varela_Round({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={varela.className}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <AppWrapper>
              <Toaster richColors />
              {children}
            </AppWrapper>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
